title: Sample Learning Lab
description: >-
    Course description
template:
    name: learninglab-template
    repo: sample-learninglab-template
before:
    - type: createIssue
      title: Week 1
      body: 1.1-Week 1 Step 1.md